    name: Generate Snake

    on:
      schedule:
        - cron: '0 0 * * *'
      workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Generate Snake
            uses: Platane/snk@v3
            with:
              github_user_name: ${{MullaiVenese03}}
              outputs: |
                dist/github-snake.svg
    ``` [5, 12]
4.  **Commit and push:** Commit the workflow file and push it to your repository [2].
5.  **Run the workflow:** Navigate to the "Actions" tab and run the workflow you just created [2, 3].
6.  **Update your README:** After the workflow runs successfully, update your profile README.md file to include the generated SVG image using an HTML `<img>` tag. For example:
    ```html
